FROM ubuntu:16.04

RUN apt update -y

# install python3 and build dependencies
RUN apt install -y \
  python3 \
  python3-dev \
  python3-pip \
  build-essential \
  git \
  libxml2-dev \
  libxslt-dev \
  zlib1g-dev \
  pandoc \
  curl

# symbolic links
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN ln -s /usr/bin/pip3 /usr/bin/pip

# pip upgrade and rdmo installation
RUN pip install --upgrade pip
RUN pip install --upgrade wheel
RUN pip install --upgrade setuptools
RUN pip install rdmo

# apache install and settings
RUN apt install -y \
  apache2 \
  libapache2-mod-wsgi-py3
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_PID_FILE=/var/run/apache2.pid
ENV APACHE_LOCK_DIR=/var/lock/apache2
COPY ./config/apache-default.conf /etc/apache2/sites-available/000-default.conf

# rdmo setup
RUN useradd -m -d /srv/rdmo -s /bin/bash rdmo
USER rdmo
RUN git clone https://github.com/rdmorganiser/rdmo-app /srv/rdmo/rdmo-app
WORKDIR /srv/rdmo/rdmo-app
COPY ./config/local_template.py /srv/rdmo/rdmo-app/config/settings/local.py
RUN python manage.py migrate
RUN python manage.py create_admin_user
RUN python manage.py download_vendor_files
RUN python manage.py collectstatic --no-input

# check and run
HEALTHCHECK --timeout=5s --interval=10s --retries=3 \
   CMD curl -f http://localhost:80 || exit 1

USER root
EXPOSE 80
COPY ./run/drun_apache.sh /
CMD ["/drun_apache.sh"]
